package FDI_Model;
// Generated 23/08/2011 12:47:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Long idCliente;
     private Usuario usuario;
     private String nombre;
     private String rucCi;
     private String direccion;
     private String telefono;
     private Set ingresoFacturados = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(Usuario usuario, String nombre, String rucCi, String direccion, String telefono) {
        this.usuario = usuario;
        this.nombre = nombre;
        this.rucCi = rucCi;
        this.direccion = direccion;
        this.telefono = telefono;
    }
    public Cliente(Usuario usuario, String nombre, String rucCi, String direccion, String telefono, Set ingresoFacturados) {
       this.usuario = usuario;
       this.nombre = nombre;
       this.rucCi = rucCi;
       this.direccion = direccion;
       this.telefono = telefono;
       this.ingresoFacturados = ingresoFacturados;
    }
   
    public Long getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Long idCliente) {
        this.idCliente = idCliente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRucCi() {
        return this.rucCi;
    }
    
    public void setRucCi(String rucCi) {
        this.rucCi = rucCi;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getIngresoFacturados() {
        return this.ingresoFacturados;
    }
    
    public void setIngresoFacturados(Set ingresoFacturados) {
        this.ingresoFacturados = ingresoFacturados;
    }




}


