package FDI_Model;
// Generated 4/09/2011 06:56:48 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="fdi_db"
)
public class Cliente  implements java.io.Serializable {


     private Long idCliente;
     private Usuario usuario;
     private String nombre;
     private String rucCi;
     private String direccion;
     private String telefono;
     private Set<IngresoFacturado> ingresoFacturados = new HashSet<IngresoFacturado>(0);

    public Cliente() {
    }

	
    public Cliente(Usuario usuario, String nombre, String rucCi, String direccion, String telefono) {
        this.usuario = usuario;
        this.nombre = nombre;
        this.rucCi = rucCi;
        this.direccion = direccion;
        this.telefono = telefono;
    }
    public Cliente(Usuario usuario, String nombre, String rucCi, String direccion, String telefono, Set<IngresoFacturado> ingresoFacturados) {
       this.usuario = usuario;
       this.nombre = nombre;
       this.rucCi = rucCi;
       this.direccion = direccion;
       this.telefono = telefono;
       this.ingresoFacturados = ingresoFacturados;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_CLIENTE", unique=true, nullable=false)
    public Long getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Long idCliente) {
        this.idCliente = idCliente;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USUARIO", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    
    @Column(name="NOMBRE", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="RUC_CI", nullable=false, length=13)
    public String getRucCi() {
        return this.rucCi;
    }
    
    public void setRucCi(String rucCi) {
        this.rucCi = rucCi;
    }
    
    @Column(name="DIRECCION", nullable=false, length=100)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="TELEFONO", nullable=false, length=15)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="cliente")
    public Set<IngresoFacturado> getIngresoFacturados() {
        return this.ingresoFacturados;
    }
    
    public void setIngresoFacturados(Set<IngresoFacturado> ingresoFacturados) {
        this.ingresoFacturados = ingresoFacturados;
    }




}


