package FDI_Model;
// Generated 23/08/2011 12:47:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ComprobanteRetencion generated by hbm2java
 */
public class ComprobanteRetencion  implements java.io.Serializable {


     private Long idComprobanteRetencion;
     private int numeroComprobante;
     private double totalRetenido;
     private byte[] imagenComprobante;
     private Set comprobanteRetencionIrs = new HashSet(0);
     private Set ingresoFacturados = new HashSet(0);
     private Set comprobanteRetencionIvas = new HashSet(0);

    public ComprobanteRetencion() {
    }

	
    public ComprobanteRetencion(int numeroComprobante, double totalRetenido) {
        this.numeroComprobante = numeroComprobante;
        this.totalRetenido = totalRetenido;
    }
    public ComprobanteRetencion(int numeroComprobante, double totalRetenido, byte[] imagenComprobante, Set comprobanteRetencionIrs, Set ingresoFacturados, Set comprobanteRetencionIvas) {
       this.numeroComprobante = numeroComprobante;
       this.totalRetenido = totalRetenido;
       this.imagenComprobante = imagenComprobante;
       this.comprobanteRetencionIrs = comprobanteRetencionIrs;
       this.ingresoFacturados = ingresoFacturados;
       this.comprobanteRetencionIvas = comprobanteRetencionIvas;
    }
   
    public Long getIdComprobanteRetencion() {
        return this.idComprobanteRetencion;
    }
    
    public void setIdComprobanteRetencion(Long idComprobanteRetencion) {
        this.idComprobanteRetencion = idComprobanteRetencion;
    }
    public int getNumeroComprobante() {
        return this.numeroComprobante;
    }
    
    public void setNumeroComprobante(int numeroComprobante) {
        this.numeroComprobante = numeroComprobante;
    }
    public double getTotalRetenido() {
        return this.totalRetenido;
    }
    
    public void setTotalRetenido(double totalRetenido) {
        this.totalRetenido = totalRetenido;
    }
    public byte[] getImagenComprobante() {
        return this.imagenComprobante;
    }
    
    public void setImagenComprobante(byte[] imagenComprobante) {
        this.imagenComprobante = imagenComprobante;
    }
    public Set getComprobanteRetencionIrs() {
        return this.comprobanteRetencionIrs;
    }
    
    public void setComprobanteRetencionIrs(Set comprobanteRetencionIrs) {
        this.comprobanteRetencionIrs = comprobanteRetencionIrs;
    }
    public Set getIngresoFacturados() {
        return this.ingresoFacturados;
    }
    
    public void setIngresoFacturados(Set ingresoFacturados) {
        this.ingresoFacturados = ingresoFacturados;
    }
    public Set getComprobanteRetencionIvas() {
        return this.comprobanteRetencionIvas;
    }
    
    public void setComprobanteRetencionIvas(Set comprobanteRetencionIvas) {
        this.comprobanteRetencionIvas = comprobanteRetencionIvas;
    }




}


