package FDI_Model;
// Generated 4/09/2011 06:56:48 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ComprobanteRetencionIr generated by hbm2java
 */
@Entity
@Table(name="comprobante_retencion_ir"
    ,catalog="fdi_db"
)
public class ComprobanteRetencionIr  implements java.io.Serializable {


     private long comprobanteRetencionIdComprobanteRetencion;
     private ComprobanteRetencion comprobanteRetencion;
     private int anio;
     private int mes;
     private double baseImponible;
     private double porcentajeRetencion;
     private double valorRetenido;

    public ComprobanteRetencionIr() {
    }

    public ComprobanteRetencionIr(long comprobanteRetencionIdComprobanteRetencion, ComprobanteRetencion comprobanteRetencion, int anio, int mes, double baseImponible, double porcentajeRetencion, double valorRetenido) {
       this.comprobanteRetencionIdComprobanteRetencion = comprobanteRetencionIdComprobanteRetencion;
       this.comprobanteRetencion = comprobanteRetencion;
       this.anio = anio;
       this.mes = mes;
       this.baseImponible = baseImponible;
       this.porcentajeRetencion = porcentajeRetencion;
       this.valorRetenido = valorRetenido;
    }
   
     @Id 
    
    @Column(name="COMPROBANTE_RETENCION_ID_COMPROBANTE_RETENCION", unique=true, nullable=false)
    public long getComprobanteRetencionIdComprobanteRetencion() {
        return this.comprobanteRetencionIdComprobanteRetencion;
    }
    
    public void setComprobanteRetencionIdComprobanteRetencion(long comprobanteRetencionIdComprobanteRetencion) {
        this.comprobanteRetencionIdComprobanteRetencion = comprobanteRetencionIdComprobanteRetencion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COMPROBANTE_RETENCION_ID_COMPROBANTE_RETENCION", unique=true, nullable=false, insertable=false, updatable=false)
    public ComprobanteRetencion getComprobanteRetencion() {
        return this.comprobanteRetencion;
    }
    
    public void setComprobanteRetencion(ComprobanteRetencion comprobanteRetencion) {
        this.comprobanteRetencion = comprobanteRetencion;
    }
    
    @Column(name="ANIO", nullable=false)
    public int getAnio() {
        return this.anio;
    }
    
    public void setAnio(int anio) {
        this.anio = anio;
    }
    
    @Column(name="MES", nullable=false)
    public int getMes() {
        return this.mes;
    }
    
    public void setMes(int mes) {
        this.mes = mes;
    }
    
    @Column(name="BASE_IMPONIBLE", nullable=false, precision=22, scale=0)
    public double getBaseImponible() {
        return this.baseImponible;
    }
    
    public void setBaseImponible(double baseImponible) {
        this.baseImponible = baseImponible;
    }
    
    @Column(name="PORCENTAJE_RETENCION", nullable=false, precision=22, scale=0)
    public double getPorcentajeRetencion() {
        return this.porcentajeRetencion;
    }
    
    public void setPorcentajeRetencion(double porcentajeRetencion) {
        this.porcentajeRetencion = porcentajeRetencion;
    }
    
    @Column(name="VALOR_RETENIDO", nullable=false, precision=22, scale=0)
    public double getValorRetenido() {
        return this.valorRetenido;
    }
    
    public void setValorRetenido(double valorRetenido) {
        this.valorRetenido = valorRetenido;
    }




}


