package FDI_Model;
// Generated 23/08/2011 12:47:11 AM by Hibernate Tools 3.2.1.GA



/**
 * ComprobanteRetencionIva generated by hbm2java
 */
public class ComprobanteRetencionIva  implements java.io.Serializable {


     private long idComprobanteRetencion;
     private ComprobanteRetencion comprobanteRetencion;
     private int anio;
     private int mes;
     private double baseImponible;
     private double porcentajeRetencion;
     private double valorRetenido;

    public ComprobanteRetencionIva() {
    }

    public ComprobanteRetencionIva(long idComprobanteRetencion, ComprobanteRetencion comprobanteRetencion, int anio, int mes, double baseImponible, double porcentajeRetencion, double valorRetenido) {
       this.idComprobanteRetencion = idComprobanteRetencion;
       this.comprobanteRetencion = comprobanteRetencion;
       this.anio = anio;
       this.mes = mes;
       this.baseImponible = baseImponible;
       this.porcentajeRetencion = porcentajeRetencion;
       this.valorRetenido = valorRetenido;
    }
   
    public long getIdComprobanteRetencion() {
        return this.idComprobanteRetencion;
    }
    
    public void setIdComprobanteRetencion(long idComprobanteRetencion) {
        this.idComprobanteRetencion = idComprobanteRetencion;
    }
    public ComprobanteRetencion getComprobanteRetencion() {
        return this.comprobanteRetencion;
    }
    
    public void setComprobanteRetencion(ComprobanteRetencion comprobanteRetencion) {
        this.comprobanteRetencion = comprobanteRetencion;
    }
    public int getAnio() {
        return this.anio;
    }
    
    public void setAnio(int anio) {
        this.anio = anio;
    }
    public int getMes() {
        return this.mes;
    }
    
    public void setMes(int mes) {
        this.mes = mes;
    }
    public double getBaseImponible() {
        return this.baseImponible;
    }
    
    public void setBaseImponible(double baseImponible) {
        this.baseImponible = baseImponible;
    }
    public double getPorcentajeRetencion() {
        return this.porcentajeRetencion;
    }
    
    public void setPorcentajeRetencion(double porcentajeRetencion) {
        this.porcentajeRetencion = porcentajeRetencion;
    }
    public double getValorRetenido() {
        return this.valorRetenido;
    }
    
    public void setValorRetenido(double valorRetenido) {
        this.valorRetenido = valorRetenido;
    }




}


