package FDI_Model;
// Generated 4/09/2011 06:56:48 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmpresaContratante generated by hbm2java
 */
@Entity
@Table(name="empresa_contratante"
    ,catalog="fdi_db"
)
public class EmpresaContratante  implements java.io.Serializable {


     private Long idEmpresaContratante;
     private String nombre;
     private Set<IngresoRelacionDependencia> ingresoRelacionDependencias = new HashSet<IngresoRelacionDependencia>(0);

    public EmpresaContratante() {
    }

	
    public EmpresaContratante(String nombre) {
        this.nombre = nombre;
    }
    public EmpresaContratante(String nombre, Set<IngresoRelacionDependencia> ingresoRelacionDependencias) {
       this.nombre = nombre;
       this.ingresoRelacionDependencias = ingresoRelacionDependencias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_EMPRESA_CONTRATANTE", unique=true, nullable=false)
    public Long getIdEmpresaContratante() {
        return this.idEmpresaContratante;
    }
    
    public void setIdEmpresaContratante(Long idEmpresaContratante) {
        this.idEmpresaContratante = idEmpresaContratante;
    }
    
    @Column(name="NOMBRE", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="empresaContratante")
    public Set<IngresoRelacionDependencia> getIngresoRelacionDependencias() {
        return this.ingresoRelacionDependencias;
    }
    
    public void setIngresoRelacionDependencias(Set<IngresoRelacionDependencia> ingresoRelacionDependencias) {
        this.ingresoRelacionDependencias = ingresoRelacionDependencias;
    }




}


