package FDI_Model;
// Generated 23/08/2011 12:47:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * EmpresaContratante generated by hbm2java
 */
public class EmpresaContratante  implements java.io.Serializable {


     private Long idEmpresaContratante;
     private String nombre;
     private Set ingresoRelacionDependencias = new HashSet(0);

    public EmpresaContratante() {
    }

	
    public EmpresaContratante(String nombre) {
        this.nombre = nombre;
    }
    public EmpresaContratante(String nombre, Set ingresoRelacionDependencias) {
       this.nombre = nombre;
       this.ingresoRelacionDependencias = ingresoRelacionDependencias;
    }
   
    public Long getIdEmpresaContratante() {
        return this.idEmpresaContratante;
    }
    
    public void setIdEmpresaContratante(Long idEmpresaContratante) {
        this.idEmpresaContratante = idEmpresaContratante;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getIngresoRelacionDependencias() {
        return this.ingresoRelacionDependencias;
    }
    
    public void setIngresoRelacionDependencias(Set ingresoRelacionDependencias) {
        this.ingresoRelacionDependencias = ingresoRelacionDependencias;
    }




}


