package FDI_Model;
// Generated 23/08/2011 12:47:11 AM by Hibernate Tools 3.2.1.GA



/**
 * FacturaTipoGastoId generated by hbm2java
 */
public class FacturaTipoGastoId  implements java.io.Serializable {


     private long idFactura;
     private long idTipoGasto;

    public FacturaTipoGastoId() {
    }

    public FacturaTipoGastoId(long idFactura, long idTipoGasto) {
       this.idFactura = idFactura;
       this.idTipoGasto = idTipoGasto;
    }
   
    public long getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(long idFactura) {
        this.idFactura = idFactura;
    }
    public long getIdTipoGasto() {
        return this.idTipoGasto;
    }
    
    public void setIdTipoGasto(long idTipoGasto) {
        this.idTipoGasto = idTipoGasto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FacturaTipoGastoId) ) return false;
		 FacturaTipoGastoId castOther = ( FacturaTipoGastoId ) other; 
         
		 return (this.getIdFactura()==castOther.getIdFactura())
 && (this.getIdTipoGasto()==castOther.getIdTipoGasto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdFactura();
         result = 37 * result + (int) this.getIdTipoGasto();
         return result;
   }   


}


