package FDI_Model;
// Generated 23/08/2011 12:47:11 AM by Hibernate Tools 3.2.1.GA



/**
 * FacturaTipoGasto generated by hbm2java
 */
public class FacturaTipoGasto  implements java.io.Serializable {


     private FacturaTipoGastoId id;
     private Factura factura;
     private TipoGasto tipoGasto;
     private double valorDeducible;

    public FacturaTipoGasto() {
    }

    public FacturaTipoGasto(FacturaTipoGastoId id, Factura factura, TipoGasto tipoGasto, double valorDeducible) {
       this.id = id;
       this.factura = factura;
       this.tipoGasto = tipoGasto;
       this.valorDeducible = valorDeducible;
    }
   
    public FacturaTipoGastoId getId() {
        return this.id;
    }
    
    public void setId(FacturaTipoGastoId id) {
        this.id = id;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public TipoGasto getTipoGasto() {
        return this.tipoGasto;
    }
    
    public void setTipoGasto(TipoGasto tipoGasto) {
        this.tipoGasto = tipoGasto;
    }
    public double getValorDeducible() {
        return this.valorDeducible;
    }
    
    public void setValorDeducible(double valorDeducible) {
        this.valorDeducible = valorDeducible;
    }




}


