package FDI_Model;
// Generated 23/08/2011 12:47:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Long idFactura;
     private TipoBienServicio tipoBienServicio;
     private Usuario usuario;
     private ProveedorCompra proveedorCompra;
     private String fecha;
     private double subtotal0;
     private double subtotalIva;
     private boolean derechoCredito;
     private double total;
     private Set facturaTipoGastos = new HashSet(0);

    public Factura() {
    }

	
    public Factura(TipoBienServicio tipoBienServicio, Usuario usuario, ProveedorCompra proveedorCompra, String fecha, double subtotal0, double subtotalIva, boolean derechoCredito, double total) {
        this.tipoBienServicio = tipoBienServicio;
        this.usuario = usuario;
        this.proveedorCompra = proveedorCompra;
        this.fecha = fecha;
        this.subtotal0 = subtotal0;
        this.subtotalIva = subtotalIva;
        this.derechoCredito = derechoCredito;
        this.total = total;
    }
    public Factura(TipoBienServicio tipoBienServicio, Usuario usuario, ProveedorCompra proveedorCompra, String fecha, double subtotal0, double subtotalIva, boolean derechoCredito, double total, Set facturaTipoGastos) {
       this.tipoBienServicio = tipoBienServicio;
       this.usuario = usuario;
       this.proveedorCompra = proveedorCompra;
       this.fecha = fecha;
       this.subtotal0 = subtotal0;
       this.subtotalIva = subtotalIva;
       this.derechoCredito = derechoCredito;
       this.total = total;
       this.facturaTipoGastos = facturaTipoGastos;
    }
   
    public Long getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Long idFactura) {
        this.idFactura = idFactura;
    }
    public TipoBienServicio getTipoBienServicio() {
        return this.tipoBienServicio;
    }
    
    public void setTipoBienServicio(TipoBienServicio tipoBienServicio) {
        this.tipoBienServicio = tipoBienServicio;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public ProveedorCompra getProveedorCompra() {
        return this.proveedorCompra;
    }
    
    public void setProveedorCompra(ProveedorCompra proveedorCompra) {
        this.proveedorCompra = proveedorCompra;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public double getSubtotal0() {
        return this.subtotal0;
    }
    
    public void setSubtotal0(double subtotal0) {
        this.subtotal0 = subtotal0;
    }
    public double getSubtotalIva() {
        return this.subtotalIva;
    }
    
    public void setSubtotalIva(double subtotalIva) {
        this.subtotalIva = subtotalIva;
    }
    public boolean isDerechoCredito() {
        return this.derechoCredito;
    }
    
    public void setDerechoCredito(boolean derechoCredito) {
        this.derechoCredito = derechoCredito;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public Set getFacturaTipoGastos() {
        return this.facturaTipoGastos;
    }
    
    public void setFacturaTipoGastos(Set facturaTipoGastos) {
        this.facturaTipoGastos = facturaTipoGastos;
    }




}


