package FDI_Model;
// Generated 4/09/2011 06:56:48 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Factura generated by hbm2java
 */
@Entity
@Table(name="factura"
    ,catalog="fdi_db"
)
public class Factura  implements java.io.Serializable {


     private Long idFactura;
     private TipoBienServicio tipoBienServicio;
     private Usuario usuario;
     private ProveedorCompra proveedorCompra;
     private Date fecha;
     private double subtotal0;
     private double subtotalIva;
     private boolean derechoCredito;
     private double total;
     private Set<FacturaTipoGasto> facturaTipoGastos = new HashSet<FacturaTipoGasto>(0);

    public Factura() {
    }

	
    public Factura(TipoBienServicio tipoBienServicio, Usuario usuario, ProveedorCompra proveedorCompra, double subtotal0, double subtotalIva, boolean derechoCredito, double total) {
        this.tipoBienServicio = tipoBienServicio;
        this.usuario = usuario;
        this.proveedorCompra = proveedorCompra;
        this.subtotal0 = subtotal0;
        this.subtotalIva = subtotalIva;
        this.derechoCredito = derechoCredito;
        this.total = total;
    }
    public Factura(TipoBienServicio tipoBienServicio, Usuario usuario, ProveedorCompra proveedorCompra, Date fecha, double subtotal0, double subtotalIva, boolean derechoCredito, double total, Set<FacturaTipoGasto> facturaTipoGastos) {
       this.tipoBienServicio = tipoBienServicio;
       this.usuario = usuario;
       this.proveedorCompra = proveedorCompra;
       this.fecha = fecha;
       this.subtotal0 = subtotal0;
       this.subtotalIva = subtotalIva;
       this.derechoCredito = derechoCredito;
       this.total = total;
       this.facturaTipoGastos = facturaTipoGastos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_FACTURA", unique=true, nullable=false)
    public Long getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Long idFactura) {
        this.idFactura = idFactura;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TIPO_BIEN_SERVICIO", nullable=false)
    public TipoBienServicio getTipoBienServicio() {
        return this.tipoBienServicio;
    }
    
    public void setTipoBienServicio(TipoBienServicio tipoBienServicio) {
        this.tipoBienServicio = tipoBienServicio;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USUARIO", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PROVEEDOR_COMPRA", nullable=false)
    public ProveedorCompra getProveedorCompra() {
        return this.proveedorCompra;
    }
    
    public void setProveedorCompra(ProveedorCompra proveedorCompra) {
        this.proveedorCompra = proveedorCompra;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="SUBTOTAL_0", nullable=false, precision=22, scale=0)
    public double getSubtotal0() {
        return this.subtotal0;
    }
    
    public void setSubtotal0(double subtotal0) {
        this.subtotal0 = subtotal0;
    }
    
    @Column(name="SUBTOTAL_IVA", nullable=false, precision=22, scale=0)
    public double getSubtotalIva() {
        return this.subtotalIva;
    }
    
    public void setSubtotalIva(double subtotalIva) {
        this.subtotalIva = subtotalIva;
    }
    
    @Column(name="DERECHO_CREDITO", nullable=false)
    public boolean isDerechoCredito() {
        return this.derechoCredito;
    }
    
    public void setDerechoCredito(boolean derechoCredito) {
        this.derechoCredito = derechoCredito;
    }
    
    @Column(name="TOTAL", nullable=false, precision=22, scale=0)
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="factura")
    public Set<FacturaTipoGasto> getFacturaTipoGastos() {
        return this.facturaTipoGastos;
    }
    
    public void setFacturaTipoGastos(Set<FacturaTipoGasto> facturaTipoGastos) {
        this.facturaTipoGastos = facturaTipoGastos;
    }




}


