package FDI_Model;
// Generated 4/09/2011 06:56:48 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FacturaTipoGasto generated by hbm2java
 */
@Entity
@Table(name="factura_tipo_gasto"
    ,catalog="fdi_db"
)
public class FacturaTipoGasto  implements java.io.Serializable {


     private FacturaTipoGastoId id;
     private Factura factura;
     private TipoGasto tipoGasto;
     private double valorDeducible;

    public FacturaTipoGasto() {
    }

    public FacturaTipoGasto(FacturaTipoGastoId id, Factura factura, TipoGasto tipoGasto, double valorDeducible) {
       this.id = id;
       this.factura = factura;
       this.tipoGasto = tipoGasto;
       this.valorDeducible = valorDeducible;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idFactura", column=@Column(name="ID_FACTURA", nullable=false) ), 
        @AttributeOverride(name="idTipoGasto", column=@Column(name="ID_TIPO_GASTO", nullable=false) ) } )
    public FacturaTipoGastoId getId() {
        return this.id;
    }
    
    public void setId(FacturaTipoGastoId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_FACTURA", nullable=false, insertable=false, updatable=false)
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TIPO_GASTO", nullable=false, insertable=false, updatable=false)
    public TipoGasto getTipoGasto() {
        return this.tipoGasto;
    }
    
    public void setTipoGasto(TipoGasto tipoGasto) {
        this.tipoGasto = tipoGasto;
    }
    
    @Column(name="VALOR_DEDUCIBLE", nullable=false, precision=22, scale=0)
    public double getValorDeducible() {
        return this.valorDeducible;
    }
    
    public void setValorDeducible(double valorDeducible) {
        this.valorDeducible = valorDeducible;
    }




}


