package FDI_Model;
// Generated 4/09/2011 06:56:48 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Formulario107 generated by hbm2java
 */
@Entity
@Table(name="formulario_107"
    ,catalog="fdi_db"
)
public class Formulario107  implements java.io.Serializable {


     private Long idFormulario107;
     private Formulario102a formulario102a;
     private Integer c102;
     private Date c103;
     private Double c301;
     private Double c303;
     private Double c305;
     private Double c307;
     private Double c309;
     private Double c311;
     private Double c313;
     private Double c315;
     private Double c317;
     private Double c319;
     private Double c321;
     private Double c323;
     private Double c325;
     private Double c327;
     private Double c329;
     private Double c331;
     private Double c351;
     private Double c353;
     private Double c401;
     private Double c403;
     private Double c405;
     private Double c407;
     private Double c409;
     private Double c411;
     private Double c413;
     private String c199;
     private Date fechaGeneracion;

    public Formulario107() {
    }

	
    public Formulario107(Formulario102a formulario102a, Date fechaGeneracion) {
        this.formulario102a = formulario102a;
        this.fechaGeneracion = fechaGeneracion;
    }
    public Formulario107(Formulario102a formulario102a, Integer c102, Date c103, Double c301, Double c303, Double c305, Double c307, Double c309, Double c311, Double c313, Double c315, Double c317, Double c319, Double c321, Double c323, Double c325, Double c327, Double c329, Double c331, Double c351, Double c353, Double c401, Double c403, Double c405, Double c407, Double c409, Double c411, Double c413, String c199, Date fechaGeneracion) {
       this.formulario102a = formulario102a;
       this.c102 = c102;
       this.c103 = c103;
       this.c301 = c301;
       this.c303 = c303;
       this.c305 = c305;
       this.c307 = c307;
       this.c309 = c309;
       this.c311 = c311;
       this.c313 = c313;
       this.c315 = c315;
       this.c317 = c317;
       this.c319 = c319;
       this.c321 = c321;
       this.c323 = c323;
       this.c325 = c325;
       this.c327 = c327;
       this.c329 = c329;
       this.c331 = c331;
       this.c351 = c351;
       this.c353 = c353;
       this.c401 = c401;
       this.c403 = c403;
       this.c405 = c405;
       this.c407 = c407;
       this.c409 = c409;
       this.c411 = c411;
       this.c413 = c413;
       this.c199 = c199;
       this.fechaGeneracion = fechaGeneracion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_FORMULARIO_107", unique=true, nullable=false)
    public Long getIdFormulario107() {
        return this.idFormulario107;
    }
    
    public void setIdFormulario107(Long idFormulario107) {
        this.idFormulario107 = idFormulario107;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_FORMULARIO_102A", nullable=false)
    public Formulario102a getFormulario102a() {
        return this.formulario102a;
    }
    
    public void setFormulario102a(Formulario102a formulario102a) {
        this.formulario102a = formulario102a;
    }
    
    @Column(name="C102")
    public Integer getC102() {
        return this.c102;
    }
    
    public void setC102(Integer c102) {
        this.c102 = c102;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="C103", length=10)
    public Date getC103() {
        return this.c103;
    }
    
    public void setC103(Date c103) {
        this.c103 = c103;
    }
    
    @Column(name="C301", precision=22, scale=0)
    public Double getC301() {
        return this.c301;
    }
    
    public void setC301(Double c301) {
        this.c301 = c301;
    }
    
    @Column(name="C303", precision=22, scale=0)
    public Double getC303() {
        return this.c303;
    }
    
    public void setC303(Double c303) {
        this.c303 = c303;
    }
    
    @Column(name="C305", precision=22, scale=0)
    public Double getC305() {
        return this.c305;
    }
    
    public void setC305(Double c305) {
        this.c305 = c305;
    }
    
    @Column(name="C307", precision=22, scale=0)
    public Double getC307() {
        return this.c307;
    }
    
    public void setC307(Double c307) {
        this.c307 = c307;
    }
    
    @Column(name="C309", precision=22, scale=0)
    public Double getC309() {
        return this.c309;
    }
    
    public void setC309(Double c309) {
        this.c309 = c309;
    }
    
    @Column(name="C311", precision=22, scale=0)
    public Double getC311() {
        return this.c311;
    }
    
    public void setC311(Double c311) {
        this.c311 = c311;
    }
    
    @Column(name="C313", precision=22, scale=0)
    public Double getC313() {
        return this.c313;
    }
    
    public void setC313(Double c313) {
        this.c313 = c313;
    }
    
    @Column(name="C315", precision=22, scale=0)
    public Double getC315() {
        return this.c315;
    }
    
    public void setC315(Double c315) {
        this.c315 = c315;
    }
    
    @Column(name="C317", precision=22, scale=0)
    public Double getC317() {
        return this.c317;
    }
    
    public void setC317(Double c317) {
        this.c317 = c317;
    }
    
    @Column(name="C319", precision=22, scale=0)
    public Double getC319() {
        return this.c319;
    }
    
    public void setC319(Double c319) {
        this.c319 = c319;
    }
    
    @Column(name="C321", precision=22, scale=0)
    public Double getC321() {
        return this.c321;
    }
    
    public void setC321(Double c321) {
        this.c321 = c321;
    }
    
    @Column(name="C323", precision=22, scale=0)
    public Double getC323() {
        return this.c323;
    }
    
    public void setC323(Double c323) {
        this.c323 = c323;
    }
    
    @Column(name="C325", precision=22, scale=0)
    public Double getC325() {
        return this.c325;
    }
    
    public void setC325(Double c325) {
        this.c325 = c325;
    }
    
    @Column(name="C327", precision=22, scale=0)
    public Double getC327() {
        return this.c327;
    }
    
    public void setC327(Double c327) {
        this.c327 = c327;
    }
    
    @Column(name="C329", precision=22, scale=0)
    public Double getC329() {
        return this.c329;
    }
    
    public void setC329(Double c329) {
        this.c329 = c329;
    }
    
    @Column(name="C331", precision=22, scale=0)
    public Double getC331() {
        return this.c331;
    }
    
    public void setC331(Double c331) {
        this.c331 = c331;
    }
    
    @Column(name="C351", precision=22, scale=0)
    public Double getC351() {
        return this.c351;
    }
    
    public void setC351(Double c351) {
        this.c351 = c351;
    }
    
    @Column(name="C353", precision=22, scale=0)
    public Double getC353() {
        return this.c353;
    }
    
    public void setC353(Double c353) {
        this.c353 = c353;
    }
    
    @Column(name="C401", precision=22, scale=0)
    public Double getC401() {
        return this.c401;
    }
    
    public void setC401(Double c401) {
        this.c401 = c401;
    }
    
    @Column(name="C403", precision=22, scale=0)
    public Double getC403() {
        return this.c403;
    }
    
    public void setC403(Double c403) {
        this.c403 = c403;
    }
    
    @Column(name="C405", precision=22, scale=0)
    public Double getC405() {
        return this.c405;
    }
    
    public void setC405(Double c405) {
        this.c405 = c405;
    }
    
    @Column(name="C407", precision=22, scale=0)
    public Double getC407() {
        return this.c407;
    }
    
    public void setC407(Double c407) {
        this.c407 = c407;
    }
    
    @Column(name="C409", precision=22, scale=0)
    public Double getC409() {
        return this.c409;
    }
    
    public void setC409(Double c409) {
        this.c409 = c409;
    }
    
    @Column(name="C411", precision=22, scale=0)
    public Double getC411() {
        return this.c411;
    }
    
    public void setC411(Double c411) {
        this.c411 = c411;
    }
    
    @Column(name="C413", precision=22, scale=0)
    public Double getC413() {
        return this.c413;
    }
    
    public void setC413(Double c413) {
        this.c413 = c413;
    }
    
    @Column(name="C199", length=13)
    public String getC199() {
        return this.c199;
    }
    
    public void setC199(String c199) {
        this.c199 = c199;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_GENERACION", nullable=false, length=10)
    public Date getFechaGeneracion() {
        return this.fechaGeneracion;
    }
    
    public void setFechaGeneracion(Date fechaGeneracion) {
        this.fechaGeneracion = fechaGeneracion;
    }




}


