package FDI_Model;
// Generated 23/08/2011 12:47:11 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Formulario102a generated by hbm2java
 */
public class Formulario102a  implements java.io.Serializable {


     private Long idFormulario102a;
     private Usuario usuario;
     private Integer c102;
     private Double c511;
     private Double c521;
     private Double c549;
     private Double c541;
     private Double c551;
     private Double c632;
     private Double c571;
     private Double c572;
     private Double c573;
     private Double c575;
     private Double c579;
     private Double c832;
     private Double c839;
     private Double c852;
     private Double c859;
     private Double c869;
     private Double c903;
     private Double c904;
     private Double c905;
     private Double c999;
     private Date fechaGeneracion;
     private boolean declaracionEfectuada;
     private boolean pagoEfectuado;
     private Set formulario107s = new HashSet(0);

    public Formulario102a() {
    }

	
    public Formulario102a(Usuario usuario, Date fechaGeneracion, boolean declaracionEfectuada, boolean pagoEfectuado) {
        this.usuario = usuario;
        this.fechaGeneracion = fechaGeneracion;
        this.declaracionEfectuada = declaracionEfectuada;
        this.pagoEfectuado = pagoEfectuado;
    }
    public Formulario102a(Usuario usuario, Integer c102, Double c511, Double c521, Double c549, Double c541, Double c551, Double c632, Double c571, Double c572, Double c573, Double c575, Double c579, Double c832, Double c839, Double c852, Double c859, Double c869, Double c903, Double c904, Double c905, Double c999, Date fechaGeneracion, boolean declaracionEfectuada, boolean pagoEfectuado, Set formulario107s) {
       this.usuario = usuario;
       this.c102 = c102;
       this.c511 = c511;
       this.c521 = c521;
       this.c549 = c549;
       this.c541 = c541;
       this.c551 = c551;
       this.c632 = c632;
       this.c571 = c571;
       this.c572 = c572;
       this.c573 = c573;
       this.c575 = c575;
       this.c579 = c579;
       this.c832 = c832;
       this.c839 = c839;
       this.c852 = c852;
       this.c859 = c859;
       this.c869 = c869;
       this.c903 = c903;
       this.c904 = c904;
       this.c905 = c905;
       this.c999 = c999;
       this.fechaGeneracion = fechaGeneracion;
       this.declaracionEfectuada = declaracionEfectuada;
       this.pagoEfectuado = pagoEfectuado;
       this.formulario107s = formulario107s;
    }
   
    public Long getIdFormulario102a() {
        return this.idFormulario102a;
    }
    
    public void setIdFormulario102a(Long idFormulario102a) {
        this.idFormulario102a = idFormulario102a;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getC102() {
        return this.c102;
    }
    
    public void setC102(Integer c102) {
        this.c102 = c102;
    }
    public Double getC511() {
        return this.c511;
    }
    
    public void setC511(Double c511) {
        this.c511 = c511;
    }
    public Double getC521() {
        return this.c521;
    }
    
    public void setC521(Double c521) {
        this.c521 = c521;
    }
    public Double getC549() {
        return this.c549;
    }
    
    public void setC549(Double c549) {
        this.c549 = c549;
    }
    public Double getC541() {
        return this.c541;
    }
    
    public void setC541(Double c541) {
        this.c541 = c541;
    }
    public Double getC551() {
        return this.c551;
    }
    
    public void setC551(Double c551) {
        this.c551 = c551;
    }
    public Double getC632() {
        return this.c632;
    }
    
    public void setC632(Double c632) {
        this.c632 = c632;
    }
    public Double getC571() {
        return this.c571;
    }
    
    public void setC571(Double c571) {
        this.c571 = c571;
    }
    public Double getC572() {
        return this.c572;
    }
    
    public void setC572(Double c572) {
        this.c572 = c572;
    }
    public Double getC573() {
        return this.c573;
    }
    
    public void setC573(Double c573) {
        this.c573 = c573;
    }
    public Double getC575() {
        return this.c575;
    }
    
    public void setC575(Double c575) {
        this.c575 = c575;
    }
    public Double getC579() {
        return this.c579;
    }
    
    public void setC579(Double c579) {
        this.c579 = c579;
    }
    public Double getC832() {
        return this.c832;
    }
    
    public void setC832(Double c832) {
        this.c832 = c832;
    }
    public Double getC839() {
        return this.c839;
    }
    
    public void setC839(Double c839) {
        this.c839 = c839;
    }
    public Double getC852() {
        return this.c852;
    }
    
    public void setC852(Double c852) {
        this.c852 = c852;
    }
    public Double getC859() {
        return this.c859;
    }
    
    public void setC859(Double c859) {
        this.c859 = c859;
    }
    public Double getC869() {
        return this.c869;
    }
    
    public void setC869(Double c869) {
        this.c869 = c869;
    }
    public Double getC903() {
        return this.c903;
    }
    
    public void setC903(Double c903) {
        this.c903 = c903;
    }
    public Double getC904() {
        return this.c904;
    }
    
    public void setC904(Double c904) {
        this.c904 = c904;
    }
    public Double getC905() {
        return this.c905;
    }
    
    public void setC905(Double c905) {
        this.c905 = c905;
    }
    public Double getC999() {
        return this.c999;
    }
    
    public void setC999(Double c999) {
        this.c999 = c999;
    }
    public Date getFechaGeneracion() {
        return this.fechaGeneracion;
    }
    
    public void setFechaGeneracion(Date fechaGeneracion) {
        this.fechaGeneracion = fechaGeneracion;
    }
    public boolean isDeclaracionEfectuada() {
        return this.declaracionEfectuada;
    }
    
    public void setDeclaracionEfectuada(boolean declaracionEfectuada) {
        this.declaracionEfectuada = declaracionEfectuada;
    }
    public boolean isPagoEfectuado() {
        return this.pagoEfectuado;
    }
    
    public void setPagoEfectuado(boolean pagoEfectuado) {
        this.pagoEfectuado = pagoEfectuado;
    }
    public Set getFormulario107s() {
        return this.formulario107s;
    }
    
    public void setFormulario107s(Set formulario107s) {
        this.formulario107s = formulario107s;
    }




}


