package FDI_Model;
// Generated 4/09/2011 06:56:48 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IngresoFacturado generated by hbm2java
 */
@Entity
@Table(name="ingreso_facturado"
    ,catalog="fdi_db"
)
public class IngresoFacturado  implements java.io.Serializable {


     private Long idIngresoFacturado;
     private Usuario usuario;
     private ComprobanteRetencion comprobanteRetencion;
     private Cliente cliente;
     private String tipo;
     private Date fecha;
     private int numeroFactura;
     private String descripcion;
     private double subtotal0;
     private double subtotalIva;
     private double total;
     private byte[] imagenFactura;
     private double totalRecibido;

    public IngresoFacturado() {
    }

	
    public IngresoFacturado(Usuario usuario, Cliente cliente, String tipo, Date fecha, int numeroFactura, String descripcion, double subtotal0, double subtotalIva, double total, double totalRecibido) {
        this.usuario = usuario;
        this.cliente = cliente;
        this.tipo = tipo;
        this.fecha = fecha;
        this.numeroFactura = numeroFactura;
        this.descripcion = descripcion;
        this.subtotal0 = subtotal0;
        this.subtotalIva = subtotalIva;
        this.total = total;
        this.totalRecibido = totalRecibido;
    }
    public IngresoFacturado(Usuario usuario, ComprobanteRetencion comprobanteRetencion, Cliente cliente, String tipo, Date fecha, int numeroFactura, String descripcion, double subtotal0, double subtotalIva, double total, byte[] imagenFactura, double totalRecibido) {
       this.usuario = usuario;
       this.comprobanteRetencion = comprobanteRetencion;
       this.cliente = cliente;
       this.tipo = tipo;
       this.fecha = fecha;
       this.numeroFactura = numeroFactura;
       this.descripcion = descripcion;
       this.subtotal0 = subtotal0;
       this.subtotalIva = subtotalIva;
       this.total = total;
       this.imagenFactura = imagenFactura;
       this.totalRecibido = totalRecibido;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_INGRESO_FACTURADO", unique=true, nullable=false)
    public Long getIdIngresoFacturado() {
        return this.idIngresoFacturado;
    }
    
    public void setIdIngresoFacturado(Long idIngresoFacturado) {
        this.idIngresoFacturado = idIngresoFacturado;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USUARIO", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_COMPROBANTE_RETENCION")
    public ComprobanteRetencion getComprobanteRetencion() {
        return this.comprobanteRetencion;
    }
    
    public void setComprobanteRetencion(ComprobanteRetencion comprobanteRetencion) {
        this.comprobanteRetencion = comprobanteRetencion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CLIENTE", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    
    @Column(name="TIPO", nullable=false, length=13)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="NUMERO_FACTURA", nullable=false)
    public int getNumeroFactura() {
        return this.numeroFactura;
    }
    
    public void setNumeroFactura(int numeroFactura) {
        this.numeroFactura = numeroFactura;
    }
    
    @Column(name="DESCRIPCION", nullable=false, length=150)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="SUBTOTAL_0", nullable=false, precision=22, scale=0)
    public double getSubtotal0() {
        return this.subtotal0;
    }
    
    public void setSubtotal0(double subtotal0) {
        this.subtotal0 = subtotal0;
    }
    
    @Column(name="SUBTOTAL_IVA", nullable=false, precision=22, scale=0)
    public double getSubtotalIva() {
        return this.subtotalIva;
    }
    
    public void setSubtotalIva(double subtotalIva) {
        this.subtotalIva = subtotalIva;
    }
    
    @Column(name="TOTAL", nullable=false, precision=22, scale=0)
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    
    @Column(name="IMAGEN_FACTURA")
    public byte[] getImagenFactura() {
        return this.imagenFactura;
    }
    
    public void setImagenFactura(byte[] imagenFactura) {
        this.imagenFactura = imagenFactura;
    }
    
    @Column(name="TOTAL_RECIBIDO", nullable=false, precision=22, scale=0)
    public double getTotalRecibido() {
        return this.totalRecibido;
    }
    
    public void setTotalRecibido(double totalRecibido) {
        this.totalRecibido = totalRecibido;
    }




}


