package FDI_Model;
// Generated 23/08/2011 12:47:11 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * IngresoFacturado generated by hbm2java
 */
public class IngresoFacturado  implements java.io.Serializable {


     private Long idIngresoFacturado;
     private Usuario usuario;
     private ComprobanteRetencion comprobanteRetencion;
     private Cliente cliente;
     private String tipo;
     private Date fecha;
     private int numeroFactura;
     private String descripcion;
     private double subtotal0;
     private double subtotalIva;
     private double total;
     private byte[] imagenFactura;
     private double totalRecibido;

    public IngresoFacturado() {
    }

	
    public IngresoFacturado(Usuario usuario, Cliente cliente, String tipo, Date fecha, int numeroFactura, String descripcion, double subtotal0, double subtotalIva, double total, double totalRecibido) {
        this.usuario = usuario;
        this.cliente = cliente;
        this.tipo = tipo;
        this.fecha = fecha;
        this.numeroFactura = numeroFactura;
        this.descripcion = descripcion;
        this.subtotal0 = subtotal0;
        this.subtotalIva = subtotalIva;
        this.total = total;
        this.totalRecibido = totalRecibido;
    }
    public IngresoFacturado(Usuario usuario, ComprobanteRetencion comprobanteRetencion, Cliente cliente, String tipo, Date fecha, int numeroFactura, String descripcion, double subtotal0, double subtotalIva, double total, byte[] imagenFactura, double totalRecibido) {
       this.usuario = usuario;
       this.comprobanteRetencion = comprobanteRetencion;
       this.cliente = cliente;
       this.tipo = tipo;
       this.fecha = fecha;
       this.numeroFactura = numeroFactura;
       this.descripcion = descripcion;
       this.subtotal0 = subtotal0;
       this.subtotalIva = subtotalIva;
       this.total = total;
       this.imagenFactura = imagenFactura;
       this.totalRecibido = totalRecibido;
    }
   
    public Long getIdIngresoFacturado() {
        return this.idIngresoFacturado;
    }
    
    public void setIdIngresoFacturado(Long idIngresoFacturado) {
        this.idIngresoFacturado = idIngresoFacturado;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public ComprobanteRetencion getComprobanteRetencion() {
        return this.comprobanteRetencion;
    }
    
    public void setComprobanteRetencion(ComprobanteRetencion comprobanteRetencion) {
        this.comprobanteRetencion = comprobanteRetencion;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getNumeroFactura() {
        return this.numeroFactura;
    }
    
    public void setNumeroFactura(int numeroFactura) {
        this.numeroFactura = numeroFactura;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public double getSubtotal0() {
        return this.subtotal0;
    }
    
    public void setSubtotal0(double subtotal0) {
        this.subtotal0 = subtotal0;
    }
    public double getSubtotalIva() {
        return this.subtotalIva;
    }
    
    public void setSubtotalIva(double subtotalIva) {
        this.subtotalIva = subtotalIva;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public byte[] getImagenFactura() {
        return this.imagenFactura;
    }
    
    public void setImagenFactura(byte[] imagenFactura) {
        this.imagenFactura = imagenFactura;
    }
    public double getTotalRecibido() {
        return this.totalRecibido;
    }
    
    public void setTotalRecibido(double totalRecibido) {
        this.totalRecibido = totalRecibido;
    }




}


