package FDI_Model;
// Generated 23/08/2011 12:47:11 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * IngresoRelacionDependencia generated by hbm2java
 */
public class IngresoRelacionDependencia  implements java.io.Serializable {


     private Long idIngresoRelacionDependencia;
     private EmpresaContratante empresaContratante;
     private Usuario usuario;
     private Date fecha;
     private String ingConcepto;
     private double ingValor;
     private String ingTipo;
     private String egrConcepto;
     private double egrValor;
     private String egrTipo;
     private double liquidoRecibido;

    public IngresoRelacionDependencia() {
    }

    public IngresoRelacionDependencia(EmpresaContratante empresaContratante, Usuario usuario, Date fecha, String ingConcepto, double ingValor, String ingTipo, String egrConcepto, double egrValor, String egrTipo, double liquidoRecibido) {
       this.empresaContratante = empresaContratante;
       this.usuario = usuario;
       this.fecha = fecha;
       this.ingConcepto = ingConcepto;
       this.ingValor = ingValor;
       this.ingTipo = ingTipo;
       this.egrConcepto = egrConcepto;
       this.egrValor = egrValor;
       this.egrTipo = egrTipo;
       this.liquidoRecibido = liquidoRecibido;
    }
   
    public Long getIdIngresoRelacionDependencia() {
        return this.idIngresoRelacionDependencia;
    }
    
    public void setIdIngresoRelacionDependencia(Long idIngresoRelacionDependencia) {
        this.idIngresoRelacionDependencia = idIngresoRelacionDependencia;
    }
    public EmpresaContratante getEmpresaContratante() {
        return this.empresaContratante;
    }
    
    public void setEmpresaContratante(EmpresaContratante empresaContratante) {
        this.empresaContratante = empresaContratante;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getIngConcepto() {
        return this.ingConcepto;
    }
    
    public void setIngConcepto(String ingConcepto) {
        this.ingConcepto = ingConcepto;
    }
    public double getIngValor() {
        return this.ingValor;
    }
    
    public void setIngValor(double ingValor) {
        this.ingValor = ingValor;
    }
    public String getIngTipo() {
        return this.ingTipo;
    }
    
    public void setIngTipo(String ingTipo) {
        this.ingTipo = ingTipo;
    }
    public String getEgrConcepto() {
        return this.egrConcepto;
    }
    
    public void setEgrConcepto(String egrConcepto) {
        this.egrConcepto = egrConcepto;
    }
    public double getEgrValor() {
        return this.egrValor;
    }
    
    public void setEgrValor(double egrValor) {
        this.egrValor = egrValor;
    }
    public String getEgrTipo() {
        return this.egrTipo;
    }
    
    public void setEgrTipo(String egrTipo) {
        this.egrTipo = egrTipo;
    }
    public double getLiquidoRecibido() {
        return this.liquidoRecibido;
    }
    
    public void setLiquidoRecibido(double liquidoRecibido) {
        this.liquidoRecibido = liquidoRecibido;
    }




}


