package FDI_Model;
// Generated 23/08/2011 12:47:11 AM by Hibernate Tools 3.2.1.GA



/**
 * Intereses generated by hbm2java
 */
public class Intereses  implements java.io.Serializable {


     private Long idIntereses;
     private int anio;
     private double trimestre1;
     private double trimestre2;
     private double trimestre3;
     private double trimestre4;

    public Intereses() {
    }

    public Intereses(int anio, double trimestre1, double trimestre2, double trimestre3, double trimestre4) {
       this.anio = anio;
       this.trimestre1 = trimestre1;
       this.trimestre2 = trimestre2;
       this.trimestre3 = trimestre3;
       this.trimestre4 = trimestre4;
    }
   
    public Long getIdIntereses() {
        return this.idIntereses;
    }
    
    public void setIdIntereses(Long idIntereses) {
        this.idIntereses = idIntereses;
    }
    public int getAnio() {
        return this.anio;
    }
    
    public void setAnio(int anio) {
        this.anio = anio;
    }
    public double getTrimestre1() {
        return this.trimestre1;
    }
    
    public void setTrimestre1(double trimestre1) {
        this.trimestre1 = trimestre1;
    }
    public double getTrimestre2() {
        return this.trimestre2;
    }
    
    public void setTrimestre2(double trimestre2) {
        this.trimestre2 = trimestre2;
    }
    public double getTrimestre3() {
        return this.trimestre3;
    }
    
    public void setTrimestre3(double trimestre3) {
        this.trimestre3 = trimestre3;
    }
    public double getTrimestre4() {
        return this.trimestre4;
    }
    
    public void setTrimestre4(double trimestre4) {
        this.trimestre4 = trimestre4;
    }




}


