package FDI_Model;
// Generated 4/09/2011 06:56:48 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Multas generated by hbm2java
 */
@Entity
@Table(name="multas"
    ,catalog="fdi_db"
)
public class Multas  implements java.io.Serializable {


     private Long idMultas;
     private String causaImpuesto;
     private Double porcentajeIr;
     private Double porcentajeIvaMensual;
     private Double porcentajeIvaSemestral;

    public Multas() {
    }

    public Multas(String causaImpuesto, Double porcentajeIr, Double porcentajeIvaMensual, Double porcentajeIvaSemestral) {
       this.causaImpuesto = causaImpuesto;
       this.porcentajeIr = porcentajeIr;
       this.porcentajeIvaMensual = porcentajeIvaMensual;
       this.porcentajeIvaSemestral = porcentajeIvaSemestral;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_MULTAS", unique=true, nullable=false)
    public Long getIdMultas() {
        return this.idMultas;
    }
    
    public void setIdMultas(Long idMultas) {
        this.idMultas = idMultas;
    }
    
    @Column(name="CAUSA_IMPUESTO", length=2)
    public String getCausaImpuesto() {
        return this.causaImpuesto;
    }
    
    public void setCausaImpuesto(String causaImpuesto) {
        this.causaImpuesto = causaImpuesto;
    }
    
    @Column(name="PORCENTAJE_IR", precision=22, scale=0)
    public Double getPorcentajeIr() {
        return this.porcentajeIr;
    }
    
    public void setPorcentajeIr(Double porcentajeIr) {
        this.porcentajeIr = porcentajeIr;
    }
    
    @Column(name="PORCENTAJE_IVA_MENSUAL", precision=22, scale=0)
    public Double getPorcentajeIvaMensual() {
        return this.porcentajeIvaMensual;
    }
    
    public void setPorcentajeIvaMensual(Double porcentajeIvaMensual) {
        this.porcentajeIvaMensual = porcentajeIvaMensual;
    }
    
    @Column(name="PORCENTAJE_IVA_SEMESTRAL", precision=22, scale=0)
    public Double getPorcentajeIvaSemestral() {
        return this.porcentajeIvaSemestral;
    }
    
    public void setPorcentajeIvaSemestral(Double porcentajeIvaSemestral) {
        this.porcentajeIvaSemestral = porcentajeIvaSemestral;
    }




}


