package FDI_Model;
// Generated 23/08/2011 12:47:11 AM by Hibernate Tools 3.2.1.GA



/**
 * Multas generated by hbm2java
 */
public class Multas  implements java.io.Serializable {


     private Long idMultas;
     private String causaImpuesto;
     private Double porcentajeIr;
     private Double porcentajeIvaMensual;
     private Double porcentajeIvaSemestral;

    public Multas() {
    }

    public Multas(String causaImpuesto, Double porcentajeIr, Double porcentajeIvaMensual, Double porcentajeIvaSemestral) {
       this.causaImpuesto = causaImpuesto;
       this.porcentajeIr = porcentajeIr;
       this.porcentajeIvaMensual = porcentajeIvaMensual;
       this.porcentajeIvaSemestral = porcentajeIvaSemestral;
    }
   
    public Long getIdMultas() {
        return this.idMultas;
    }
    
    public void setIdMultas(Long idMultas) {
        this.idMultas = idMultas;
    }
    public String getCausaImpuesto() {
        return this.causaImpuesto;
    }
    
    public void setCausaImpuesto(String causaImpuesto) {
        this.causaImpuesto = causaImpuesto;
    }
    public Double getPorcentajeIr() {
        return this.porcentajeIr;
    }
    
    public void setPorcentajeIr(Double porcentajeIr) {
        this.porcentajeIr = porcentajeIr;
    }
    public Double getPorcentajeIvaMensual() {
        return this.porcentajeIvaMensual;
    }
    
    public void setPorcentajeIvaMensual(Double porcentajeIvaMensual) {
        this.porcentajeIvaMensual = porcentajeIvaMensual;
    }
    public Double getPorcentajeIvaSemestral() {
        return this.porcentajeIvaSemestral;
    }
    
    public void setPorcentajeIvaSemestral(Double porcentajeIvaSemestral) {
        this.porcentajeIvaSemestral = porcentajeIvaSemestral;
    }




}


