package FDI_Model;
// Generated 23/08/2011 12:47:11 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PlazosIva generated by hbm2java
 */
public class PlazosIva  implements java.io.Serializable {


     private Long idPlazosIva;
     private Date fechaPublicacion;
     private int novenoDigitoRuc;
     private int mensual;
     private Date semestre1;
     private Date semestre2;

    public PlazosIva() {
    }

    public PlazosIva(Date fechaPublicacion, int novenoDigitoRuc, int mensual, Date semestre1, Date semestre2) {
       this.fechaPublicacion = fechaPublicacion;
       this.novenoDigitoRuc = novenoDigitoRuc;
       this.mensual = mensual;
       this.semestre1 = semestre1;
       this.semestre2 = semestre2;
    }
   
    public Long getIdPlazosIva() {
        return this.idPlazosIva;
    }
    
    public void setIdPlazosIva(Long idPlazosIva) {
        this.idPlazosIva = idPlazosIva;
    }
    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }
    
    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }
    public int getNovenoDigitoRuc() {
        return this.novenoDigitoRuc;
    }
    
    public void setNovenoDigitoRuc(int novenoDigitoRuc) {
        this.novenoDigitoRuc = novenoDigitoRuc;
    }
    public int getMensual() {
        return this.mensual;
    }
    
    public void setMensual(int mensual) {
        this.mensual = mensual;
    }
    public Date getSemestre1() {
        return this.semestre1;
    }
    
    public void setSemestre1(Date semestre1) {
        this.semestre1 = semestre1;
    }
    public Date getSemestre2() {
        return this.semestre2;
    }
    
    public void setSemestre2(Date semestre2) {
        this.semestre2 = semestre2;
    }




}


