package FDI_Model;
// Generated 4/09/2011 06:56:48 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PlazosIr generated by hbm2java
 */
@Entity
@Table(name="plazos_ir"
    ,catalog="fdi_db"
)
public class PlazosIr  implements java.io.Serializable {


     private Long idPlazosIr;
     private int novenoDigitoRuc;
     private Date personasNaturales;

    public PlazosIr() {
    }

    public PlazosIr(int novenoDigitoRuc, Date personasNaturales) {
       this.novenoDigitoRuc = novenoDigitoRuc;
       this.personasNaturales = personasNaturales;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_PLAZOS_IR", unique=true, nullable=false)
    public Long getIdPlazosIr() {
        return this.idPlazosIr;
    }
    
    public void setIdPlazosIr(Long idPlazosIr) {
        this.idPlazosIr = idPlazosIr;
    }
    
    @Column(name="NOVENO_DIGITO_RUC", nullable=false)
    public int getNovenoDigitoRuc() {
        return this.novenoDigitoRuc;
    }
    
    public void setNovenoDigitoRuc(int novenoDigitoRuc) {
        this.novenoDigitoRuc = novenoDigitoRuc;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="PERSONAS_NATURALES", nullable=false, length=10)
    public Date getPersonasNaturales() {
        return this.personasNaturales;
    }
    
    public void setPersonasNaturales(Date personasNaturales) {
        this.personasNaturales = personasNaturales;
    }




}


