package FDI_Model;
// Generated 23/08/2011 12:47:11 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PlazosIr generated by hbm2java
 */
public class PlazosIr  implements java.io.Serializable {


     private Long idPlazosIr;
     private int novenoDigitoRuc;
     private Date personasNaturales;

    public PlazosIr() {
    }

    public PlazosIr(int novenoDigitoRuc, Date personasNaturales) {
       this.novenoDigitoRuc = novenoDigitoRuc;
       this.personasNaturales = personasNaturales;
    }
   
    public Long getIdPlazosIr() {
        return this.idPlazosIr;
    }
    
    public void setIdPlazosIr(Long idPlazosIr) {
        this.idPlazosIr = idPlazosIr;
    }
    public int getNovenoDigitoRuc() {
        return this.novenoDigitoRuc;
    }
    
    public void setNovenoDigitoRuc(int novenoDigitoRuc) {
        this.novenoDigitoRuc = novenoDigitoRuc;
    }
    public Date getPersonasNaturales() {
        return this.personasNaturales;
    }
    
    public void setPersonasNaturales(Date personasNaturales) {
        this.personasNaturales = personasNaturales;
    }




}


