package FDI_Model;
// Generated 4/09/2011 06:56:48 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PlazosIva generated by hbm2java
 */
@Entity
@Table(name="plazos_iva"
    ,catalog="fdi_db"
)
public class PlazosIva  implements java.io.Serializable {


     private Long idPlazosIva;
     private Date fechaPublicacion;
     private int novenoDigitoRuc;
     private int mensual;
     private int semestre1;
     private int semestre2;

    public PlazosIva() {
    }

    public PlazosIva(Date fechaPublicacion, int novenoDigitoRuc, int mensual, int semestre1, int semestre2) {
       this.fechaPublicacion = fechaPublicacion;
       this.novenoDigitoRuc = novenoDigitoRuc;
       this.mensual = mensual;
       this.semestre1 = semestre1;
       this.semestre2 = semestre2;
    }

    @Override
    public String toString() {
        return "PlazosIva{" + "idPlazosIva=" + idPlazosIva + ", fechaPublicacion=" + fechaPublicacion + ", novenoDigitoRuc=" + novenoDigitoRuc + ", mensual=" + mensual + ", semestre1=" + semestre1 + ", semestre2=" + semestre2 + '}';
    }

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="ID_PLAZOS_IVA", unique=true, nullable=false)
    public Long getIdPlazosIva() {
        return this.idPlazosIva;
    }
    
    public void setIdPlazosIva(Long idPlazosIva) {
        this.idPlazosIva = idPlazosIva;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_PUBLICACION", nullable=false, length=10)
    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }
    
    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }
    
    @Column(name="NOVENO_DIGITO_RUC", nullable=false)
    public int getNovenoDigitoRuc() {
        return this.novenoDigitoRuc;
    }
    
    public void setNovenoDigitoRuc(int novenoDigitoRuc) {
        this.novenoDigitoRuc = novenoDigitoRuc;
    }
    
    @Column(name="MENSUAL", nullable=false)
    public int getMensual() {
        return this.mensual;
    }
    
    public void setMensual(int mensual) {
        this.mensual = mensual;
    }
    
    @Column(name="SEMESTRE_1", nullable=false)
    public int getSemestre1() {
        return this.semestre1;
    }
    
    public void setSemestre1(int semestre1) {
        this.semestre1 = semestre1;
    }
    
    @Column(name="SEMESTRE_2", nullable=false)
    public int getSemestre2() {
        return this.semestre2;
    }
    
    public void setSemestre2(int semestre2) {
        this.semestre2 = semestre2;
    }




}


