package FDI_Model;
// Generated 4/09/2011 06:56:48 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PorcentajeRetencionIr generated by hbm2java
 */
@Entity
@Table(name="porcentaje_retencion_ir"
    ,catalog="fdi_db"
)
public class PorcentajeRetencionIr  implements java.io.Serializable {


     private Long idPorcentajeRetencionIr;
     private Date fechaPublicacion;
     private double valorPorcentual;

    public PorcentajeRetencionIr() {
    }

    public PorcentajeRetencionIr(Date fechaPublicacion, double valorPorcentual) {
       this.fechaPublicacion = fechaPublicacion;
       this.valorPorcentual = valorPorcentual;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_PORCENTAJE_RETENCION_IR", unique=true, nullable=false)
    public Long getIdPorcentajeRetencionIr() {
        return this.idPorcentajeRetencionIr;
    }
    
    public void setIdPorcentajeRetencionIr(Long idPorcentajeRetencionIr) {
        this.idPorcentajeRetencionIr = idPorcentajeRetencionIr;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_PUBLICACION", nullable=false, length=10)
    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }
    
    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }
    
    @Column(name="VALOR_PORCENTUAL", nullable=false, precision=22, scale=0)
    public double getValorPorcentual() {
        return this.valorPorcentual;
    }
    
    public void setValorPorcentual(double valorPorcentual) {
        this.valorPorcentual = valorPorcentual;
    }




}


