package FDI_Model;
// Generated 23/08/2011 12:47:11 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PorcentajeRetencionIr generated by hbm2java
 */
public class PorcentajeRetencionIr  implements java.io.Serializable {


     private Long idPorcentajeRetencionIr;
     private Date fechaPublicacion;
     private double valorPorcentual;

    public PorcentajeRetencionIr() {
    }

    public PorcentajeRetencionIr(Date fechaPublicacion, double valorPorcentual) {
       this.fechaPublicacion = fechaPublicacion;
       this.valorPorcentual = valorPorcentual;
    }
   
    public Long getIdPorcentajeRetencionIr() {
        return this.idPorcentajeRetencionIr;
    }
    
    public void setIdPorcentajeRetencionIr(Long idPorcentajeRetencionIr) {
        this.idPorcentajeRetencionIr = idPorcentajeRetencionIr;
    }
    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }
    
    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }
    public double getValorPorcentual() {
        return this.valorPorcentual;
    }
    
    public void setValorPorcentual(double valorPorcentual) {
        this.valorPorcentual = valorPorcentual;
    }




}


