package FDI_Model;
// Generated 4/09/2011 06:56:48 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PorcentajesSobreBaseIr generated by hbm2java
 */
@Entity
@Table(name="porcentajes_sobre_base_ir"
    ,catalog="fdi_db"
)
public class PorcentajesSobreBaseIr  implements java.io.Serializable {


     private Long idPorcentajesSobreBaseIr;
     private int anio;
     private double fraccionBasica;
     private double excesoHasta;
     private double impuestoFraccionBasica;
     private double procentajeImpuestoFraccionExcedente;

    public PorcentajesSobreBaseIr() {
    }

    public PorcentajesSobreBaseIr(int anio, double fraccionBasica, double excesoHasta, double impuestoFraccionBasica, double procentajeImpuestoFraccionExcedente) {
       this.anio = anio;
       this.fraccionBasica = fraccionBasica;
       this.excesoHasta = excesoHasta;
       this.impuestoFraccionBasica = impuestoFraccionBasica;
       this.procentajeImpuestoFraccionExcedente = procentajeImpuestoFraccionExcedente;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_PORCENTAJES_SOBRE_BASE_IR", unique=true, nullable=false)
    public Long getIdPorcentajesSobreBaseIr() {
        return this.idPorcentajesSobreBaseIr;
    }
    
    public void setIdPorcentajesSobreBaseIr(Long idPorcentajesSobreBaseIr) {
        this.idPorcentajesSobreBaseIr = idPorcentajesSobreBaseIr;
    }
    
    @Column(name="ANIO", nullable=false)
    public int getAnio() {
        return this.anio;
    }
    
    public void setAnio(int anio) {
        this.anio = anio;
    }
    
    @Column(name="FRACCION_BASICA", nullable=false, precision=22, scale=0)
    public double getFraccionBasica() {
        return this.fraccionBasica;
    }
    
    public void setFraccionBasica(double fraccionBasica) {
        this.fraccionBasica = fraccionBasica;
    }
    
    @Column(name="EXCESO_HASTA", nullable=false, precision=22, scale=0)
    public double getExcesoHasta() {
        return this.excesoHasta;
    }
    
    public void setExcesoHasta(double excesoHasta) {
        this.excesoHasta = excesoHasta;
    }
    
    @Column(name="IMPUESTO_FRACCION_BASICA", nullable=false, precision=22, scale=0)
    public double getImpuestoFraccionBasica() {
        return this.impuestoFraccionBasica;
    }
    
    public void setImpuestoFraccionBasica(double impuestoFraccionBasica) {
        this.impuestoFraccionBasica = impuestoFraccionBasica;
    }
    
    @Column(name="PROCENTAJE_IMPUESTO_FRACCION_EXCEDENTE", nullable=false, precision=22, scale=0)
    public double getProcentajeImpuestoFraccionExcedente() {
        return this.procentajeImpuestoFraccionExcedente;
    }
    
    public void setProcentajeImpuestoFraccionExcedente(double procentajeImpuestoFraccionExcedente) {
        this.procentajeImpuestoFraccionExcedente = procentajeImpuestoFraccionExcedente;
    }




}


