package FDI_Model;
// Generated 4/09/2011 06:56:48 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProveedorCompra generated by hbm2java
 */
@Entity
@Table(name="proveedor_compra"
    ,catalog="fdi_db"
)
public class ProveedorCompra  implements java.io.Serializable {


     private Long idProveedorCompra;
     private String rucCi;
     private String razonSocial;
     private String direccion;
     private String ubiGoogleMaps;
     private String telefono;
     private Set<Factura> facturas = new HashSet<Factura>(0);

    public ProveedorCompra() {
    }

	
    public ProveedorCompra(String rucCi, String razonSocial, String direccion) {
        this.rucCi = rucCi;
        this.razonSocial = razonSocial;
        this.direccion = direccion;
    }
    public ProveedorCompra(String rucCi, String razonSocial, String direccion, String ubiGoogleMaps, String telefono, Set<Factura> facturas) {
       this.rucCi = rucCi;
       this.razonSocial = razonSocial;
       this.direccion = direccion;
       this.ubiGoogleMaps = ubiGoogleMaps;
       this.telefono = telefono;
       this.facturas = facturas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_PROVEEDOR_COMPRA", unique=true, nullable=false)
    public Long getIdProveedorCompra() {
        return this.idProveedorCompra;
    }
    
    public void setIdProveedorCompra(Long idProveedorCompra) {
        this.idProveedorCompra = idProveedorCompra;
    }
    
    @Column(name="RUC_CI", nullable=false, length=13)
    public String getRucCi() {
        return this.rucCi;
    }
    
    public void setRucCi(String rucCi) {
        this.rucCi = rucCi;
    }
    
    @Column(name="RAZON_SOCIAL", nullable=false, length=45)
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    
    @Column(name="DIRECCION", nullable=false, length=100)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="UBI_GOOGLE_MAPS", length=100)
    public String getUbiGoogleMaps() {
        return this.ubiGoogleMaps;
    }
    
    public void setUbiGoogleMaps(String ubiGoogleMaps) {
        this.ubiGoogleMaps = ubiGoogleMaps;
    }
    
    @Column(name="TELEFONO", length=20)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="proveedorCompra")
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }




}


