package FDI_Model;
// Generated 4/09/2011 06:56:48 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoBienServicio generated by hbm2java
 */
@Entity
@Table(name="tipo_bien_servicio"
    ,catalog="fdi_db"
)
public class TipoBienServicio  implements java.io.Serializable {


     private Long idTipoBienServicio;
     private String nombre;
     private Set<Factura> facturas = new HashSet<Factura>(0);

    public TipoBienServicio() {
    }

	
    public TipoBienServicio(String nombre) {
        this.nombre = nombre;
    }
    public TipoBienServicio(String nombre, Set<Factura> facturas) {
       this.nombre = nombre;
       this.facturas = facturas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_TIPO_BIEN_SERVICIO", unique=true, nullable=false)
    public Long getIdTipoBienServicio() {
        return this.idTipoBienServicio;
    }
    
    public void setIdTipoBienServicio(Long idTipoBienServicio) {
        this.idTipoBienServicio = idTipoBienServicio;
    }
    
    @Column(name="NOMBRE", nullable=false, length=40)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tipoBienServicio")
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }




}


