package FDI_Model;
// Generated 23/08/2011 12:47:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoGasto generated by hbm2java
 */
public class TipoGasto  implements java.io.Serializable {


     private Long idTipoGasto;
     private String nombre;
     private Set facturaTipoGastos = new HashSet(0);

    public TipoGasto() {
    }

	
    public TipoGasto(String nombre) {
        this.nombre = nombre;
    }
    public TipoGasto(String nombre, Set facturaTipoGastos) {
       this.nombre = nombre;
       this.facturaTipoGastos = facturaTipoGastos;
    }
   
    public Long getIdTipoGasto() {
        return this.idTipoGasto;
    }
    
    public void setIdTipoGasto(Long idTipoGasto) {
        this.idTipoGasto = idTipoGasto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getFacturaTipoGastos() {
        return this.facturaTipoGastos;
    }
    
    public void setFacturaTipoGastos(Set facturaTipoGastos) {
        this.facturaTipoGastos = facturaTipoGastos;
    }




}


