package FDI_Model;
// Generated 23/08/2011 12:47:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoBienServicio generated by hbm2java
 */
public class TipoBienServicio  implements java.io.Serializable {


     private Long idTipoBienServicio;
     private String nombre;
     private Set facturas = new HashSet(0);

    public TipoBienServicio() {
    }

	
    public TipoBienServicio(String nombre) {
        this.nombre = nombre;
    }
    public TipoBienServicio(String nombre, Set facturas) {
       this.nombre = nombre;
       this.facturas = facturas;
    }
   
    public Long getIdTipoBienServicio() {
        return this.idTipoBienServicio;
    }
    
    public void setIdTipoBienServicio(Long idTipoBienServicio) {
        this.idTipoBienServicio = idTipoBienServicio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


