package FDI_Model;
// Generated 4/09/2011 06:56:48 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="fdi_db"
)
public class Usuario  implements java.io.Serializable {


     private Long idUsuario;
     private String contrasenia;
     private String tipoIdentificacionUsuario;
     private String numIdentificacionUsuario;
     private String razonSocial;
     private String tipoIdentificacionContribuyente;
     private String numIdentificacionContribuyente;
     private String periodoDeclaracionIva;
     private String email;
     private String provincia;
     private String ciudad;
     private boolean alertaIva;
     private boolean alertaIr;
     private Set<IngresoFacturado> ingresoFacturados = new HashSet<IngresoFacturado>(0);
     private Set<IngresoRelacionDependencia> ingresoRelacionDependencias = new HashSet<IngresoRelacionDependencia>(0);
     private Set<Cliente> clientes = new HashSet<Cliente>(0);
     private Set<Factura> facturas = new HashSet<Factura>(0);
     private Set<Formulario104a> formulario104as = new HashSet<Formulario104a>(0);
     private Set<Formulario102a> formulario102as = new HashSet<Formulario102a>(0);

    public Usuario() {
    }

	
    public Usuario(String contrasenia, String tipoIdentificacionUsuario, String numIdentificacionUsuario, String razonSocial, String tipoIdentificacionContribuyente, String numIdentificacionContribuyente, String periodoDeclaracionIva, String provincia, String ciudad, boolean alertaIva, boolean alertaIr) {
        this.contrasenia = contrasenia;
        this.tipoIdentificacionUsuario = tipoIdentificacionUsuario;
        this.numIdentificacionUsuario = numIdentificacionUsuario;
        this.razonSocial = razonSocial;
        this.tipoIdentificacionContribuyente = tipoIdentificacionContribuyente;
        this.numIdentificacionContribuyente = numIdentificacionContribuyente;
        this.periodoDeclaracionIva = periodoDeclaracionIva;
        this.provincia = provincia;
        this.ciudad = ciudad;
        this.alertaIva = alertaIva;
        this.alertaIr = alertaIr;
    }
    public Usuario(String contrasenia, String tipoIdentificacionUsuario, String numIdentificacionUsuario, String razonSocial, String tipoIdentificacionContribuyente, String numIdentificacionContribuyente, String periodoDeclaracionIva, String email, String provincia, String ciudad, boolean alertaIva, boolean alertaIr, Set<IngresoFacturado> ingresoFacturados, Set<IngresoRelacionDependencia> ingresoRelacionDependencias, Set<Cliente> clientes, Set<Factura> facturas, Set<Formulario104a> formulario104as, Set<Formulario102a> formulario102as) {
       this.contrasenia = contrasenia;
       this.tipoIdentificacionUsuario = tipoIdentificacionUsuario;
       this.numIdentificacionUsuario = numIdentificacionUsuario;
       this.razonSocial = razonSocial;
       this.tipoIdentificacionContribuyente = tipoIdentificacionContribuyente;
       this.numIdentificacionContribuyente = numIdentificacionContribuyente;
       this.periodoDeclaracionIva = periodoDeclaracionIva;
       this.email = email;
       this.provincia = provincia;
       this.ciudad = ciudad;
       this.alertaIva = alertaIva;
       this.alertaIr = alertaIr;
       this.ingresoFacturados = ingresoFacturados;
       this.ingresoRelacionDependencias = ingresoRelacionDependencias;
       this.clientes = clientes;
       this.facturas = facturas;
       this.formulario104as = formulario104as;
       this.formulario102as = formulario102as;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_USUARIO", unique=true, nullable=false)
    public Long getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Long idUsuario) {
        this.idUsuario = idUsuario;
    }
    
    @Column(name="CONTRASENIA", nullable=false, length=20)
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    
    @Column(name="TIPO_IDENTIFICACION_USUARIO", nullable=false, length=3)
    public String getTipoIdentificacionUsuario() {
        return this.tipoIdentificacionUsuario;
    }
    
    public void setTipoIdentificacionUsuario(String tipoIdentificacionUsuario) {
        this.tipoIdentificacionUsuario = tipoIdentificacionUsuario;
    }
    
    @Column(name="NUM_IDENTIFICACION_USUARIO", nullable=false, length=13)
    public String getNumIdentificacionUsuario() {
        return this.numIdentificacionUsuario;
    }
    
    public void setNumIdentificacionUsuario(String numIdentificacionUsuario) {
        this.numIdentificacionUsuario = numIdentificacionUsuario;
    }
    
    @Column(name="RAZON_SOCIAL", nullable=false, length=45)
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    
    @Column(name="TIPO_IDENTIFICACION_CONTRIBUYENTE", nullable=false, length=3)
    public String getTipoIdentificacionContribuyente() {
        return this.tipoIdentificacionContribuyente;
    }
    
    public void setTipoIdentificacionContribuyente(String tipoIdentificacionContribuyente) {
        this.tipoIdentificacionContribuyente = tipoIdentificacionContribuyente;
    }
    
    @Column(name="NUM_IDENTIFICACION_CONTRIBUYENTE", nullable=false, length=13)
    public String getNumIdentificacionContribuyente() {
        return this.numIdentificacionContribuyente;
    }
    
    public void setNumIdentificacionContribuyente(String numIdentificacionContribuyente) {
        this.numIdentificacionContribuyente = numIdentificacionContribuyente;
    }
    
    @Column(name="PERIODO_DECLARACION_IVA", nullable=false, length=9)
    public String getPeriodoDeclaracionIva() {
        return this.periodoDeclaracionIva;
    }
    
    public void setPeriodoDeclaracionIva(String periodoDeclaracionIva) {
        this.periodoDeclaracionIva = periodoDeclaracionIva;
    }
    
    @Column(name="EMAIL", length=40)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="PROVINCIA", nullable=false, length=20)
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    
    @Column(name="CIUDAD", nullable=false, length=20)
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    
    @Column(name="ALERTA_IVA", nullable=false)
    public boolean isAlertaIva() {
        return this.alertaIva;
    }
    
    public void setAlertaIva(boolean alertaIva) {
        this.alertaIva = alertaIva;
    }
    
    @Column(name="ALERTA_IR", nullable=false)
    public boolean isAlertaIr() {
        return this.alertaIr;
    }
    
    public void setAlertaIr(boolean alertaIr) {
        this.alertaIr = alertaIr;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<IngresoFacturado> getIngresoFacturados() {
        return this.ingresoFacturados;
    }
    
    public void setIngresoFacturados(Set<IngresoFacturado> ingresoFacturados) {
        this.ingresoFacturados = ingresoFacturados;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<IngresoRelacionDependencia> getIngresoRelacionDependencias() {
        return this.ingresoRelacionDependencias;
    }
    
    public void setIngresoRelacionDependencias(Set<IngresoRelacionDependencia> ingresoRelacionDependencias) {
        this.ingresoRelacionDependencias = ingresoRelacionDependencias;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Formulario104a> getFormulario104as() {
        return this.formulario104as;
    }
    
    public void setFormulario104as(Set<Formulario104a> formulario104as) {
        this.formulario104as = formulario104as;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Formulario102a> getFormulario102as() {
        return this.formulario102as;
    }
    
    public void setFormulario102as(Set<Formulario102a> formulario102as) {
        this.formulario102as = formulario102as;
    }




}


